---
- name: Create appuio-infra project
  openshift_project:
    name: appuio-infra

- name: Instantiate pruner template
  openshift_resource:
    namespace: appuio-infra
    template: "{{ role_path }}/files/pruner-template.yml"
    app_name: appuio-pruner
    arguments:
      PRUNER_SOURCE: "{{ role_src | default('https://github.com/appuio/appuio-pruner.git') }}"
      PRUNER_VERSION: "{{ role_version | default('master') }}"
      TIMEZONE: "{{ appuio_container_timezone | default('UTC') }}"
      OC_URL: "{{ oc_url | default('https://console.appuio.ch/console/extensions/clients/linux/oc') }}"

- name: Configure permissions for pruner service account
  openshift_policy:
    cluster_roles:
      - edit
      - system:image-pruner
    users: system:serviceaccount:appuio-infra:default
